AppBundle\Document\Address:
    type: embeddedDocument
    fields:
        street1:
            type: string
        street2:
            type: string
        city:
            type: string
        state:
            type: string
        zip:
            type: string
        phone:
            type: string