version: '2'
services:
  api:
      image: icox/symfony:php7-dev
      volumes:
        - .:/var/www
  elastic:
      expose:
        - 5601
        - 9200
        - 9300
  kibana:
      image: kibana
      environment:
        - ELASTICSEARCH_URL=http://elastic:9200