imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: elastic.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: "%mongodb_database%"
    document_managers:
        default:
            auto_mapping: true

sensio_framework_extra:
    request: { converters: true }

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            AppBundle:
                namespace_prefix: "AppBundle"
                path: "@AppBundle/Resources/config/serializer"
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@AppBundle/Resources/config/serializer"
            SIC:
                namespace_prefix: "SIC"
                path: "@AppBundle/Resources/config/serializer"

fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    body_listener: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
        xml: true
        html: true
    view:
        view_response_listener: force
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        exception_wrapper_handler:  null
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }
            - { path: ^/oauth, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }
    body_converter:
        enabled: true
        validate: true
    exception:
        enabled: true
        codes:
            'Symfony\Component\HttpKernel\Exception\HttpException': 500
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true

nelmio_api_doc:
    name: UCI API

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: true
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
            max_age: 3600
        '^/oauth/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET']
            max_age: 3600