fos_elastica:
    clients:
        default:
            host: elastic
            port: 9200
    indexes:
        uci:
            index_name: uci
            use_alias: true
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: English
                            stopwords:
                                type:      stop
                                stopwords: [_english_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                sic:
                    mappings:
                        id: { boost: 1, analyzer: custom_analyzer }
                        code: { boost: 2, analyzer: custom_analyzer }
                        office: { boost: 3, analyzer: custom_analyzer }
                        title: { boost: 4, analyzer: custom_analyzer }
                    persistence:
                        driver: mongodb
                        model: AppBundle\Document\SIC
                        provider: ~
                        listener:
                            logger: true
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                company:
                    mappings:
                        id: { boost: 1, analyzer: custom_analyzer }
                        cik: { boost: 2, analyzer: custom_analyzer }
                        conformedName: { boost: 6, analyzer: custom_analyzer }
                        assignedSIC:
                            type: "nested"
                            properties:
                                id: { analyzer: custom_analyzer }
                                code: { analyzer: custom_analyzer }
                                title: { analyzer: custom_analyzer }
                        stateOfIncorporation: { analyzer: custom_analyzer }
                        fiscalEndYear: { analyzer: custom_analyzer }
                        businessAddress:
                            type: "nested"
                            properties:
                                street1: { analyzer: custom_analyzer }
                                street2: { analyzer: custom_analyzer }
                                city: { analyzer: custom_analyzer }
                                state: { analyzer: custom_analyzer }
                                zip: { analyzer: custom_analyzer }
                                phone: { analyzer: custom_analyzer }
                        mailAddress:
                            type: "nested"
                            properties:
                                street1: { analyzer: custom_analyzer }
                                street2: { analyzer: custom_analyzer }
                                city: { analyzer: custom_analyzer }
                                state: { analyzer: custom_analyzer }
                                zip: { analyzer: custom_analyzer }
                                phone: { analyzer: custom_analyzer }
                        owner:
                            type: "nested"
                            properties:
                                conformedName: { boost: 5, analyzer: custom_analyzer }
                                cik: { analyzer: custom_analyzer }
                                mailAddress:
                                    type: "nested"
                                    properties:
                                        street1: { analyzer: custom_analyzer }
                                        street2: { analyzer: custom_analyzer }
                                        city: { analyzer: custom_analyzer }
                                        state: { analyzer: custom_analyzer }
                                        zip: { analyzer: custom_analyzer }
                                        phone: { analyzer: custom_analyzer }
                        getGeoPoint:
                            type: geo_point
                    persistence:
                        driver: mongodb
                        model: AppBundle\Document\Company
                        provider: ~
                        listener:
                            logger: true
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true