fos_elastica:
    clients:
        default:
            host: elastic
            port: 9200
    indexes:
        uci:
            index_name: uci
            use_alias: true
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: English
                            stopwords:
                                type:      stop
                                stopwords: [_english_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                sic:
                    mappings:
                        id: { boost: 1, type: string, index: not_analyzed }
                        code: { boost: 2, type: string, index: not_analyzed }
                        office: { boost: 3, analyzer: custom_analyzer }
                        title: { boost: 4, analyzer: custom_analyzer }
                    persistence:
                        driver: mongodb
                        model: AppBundle\Document\SIC
                        provider: ~
                        listener:
                            logger: true
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                company:
                    mappings:
                        id: { boost: 1, type: string, index: not_analyzed }
                        cik: { boost: 2, type: string, index: not_analyzed }
                        conformedName: { boost: 4, type: string, analyzer: custom_analyzer }
                        assignedSIC:
                            type: nested
                            properties:
                                id: { type: string, index: not_analyzed }
                                code: { type: string, index: not_analyzed }
                                title: { type: string, analyzer: custom_analyzer }
                        stateOfIncorporation: { type: string, analyzer: custom_analyzer }
                        fiscalEndYear: { type: string, index: not_analyzed }
                        businessAddress:
                            type: nested
                            properties:
                                street1: { type: string, analyzer: custom_analyzer }
                                street2: { type: string, analyzer: custom_analyzer }
                                city: { type: string, analyzer: custom_analyzer }
                                city_raw: { type: string, index: not_analyzed }
                                state: { type: string, analyzer: custom_analyzer }
                                state_raw: { type: string, index: not_analyzed }
                                zip: { type: string, index: not_analyzed }
                                phone: { type: string, index: not_analyzed }
                        mailAddress:
                            type: nested
                            properties:
                                street1: { type: string, analyzer: custom_analyzer }
                                street2: { type: string, analyzer: custom_analyzer }
                                city: { type: string, analyzer: custom_analyzer }
                                city_raw: { type: string, index: not_analyzed }
                                state: { type: string, analyzer: custom_analyzer }
                                state_raw: { type: string, index: not_analyzed }
                                zip: { type: string, index: not_analyzed }
                                phone: { type: string, index: not_analyzed }
                        owner:
                            type: nested
                            properties:
                                conformedName: { boost: 3, type: string, analyzer: custom_analyzer }
                                cik: { type: string, analyzer: custom_analyzer }
                                mailAddress:
                                    type: nested
                                    properties:
                                      street1: { type: string, analyzer: custom_analyzer }
                                      street2: { type: string, analyzer: custom_analyzer }
                                      city: { type: string, analyzer: custom_analyzer }
                                      city_raw: { type: string, index: not_analyzed }
                                      state: { type: string, analyzer: custom_analyzer }
                                      state_raw: { type: string, index: not_analyzed }
                                      zip: { type: string, index: not_analyzed }
                                      phone: { type: string, index: not_analyzed }
                        getGeoPoint:
                            type: geo_point
                    persistence:
                        driver: mongodb
                        model: AppBundle\Document\Company
                        provider: ~
                        listener:
                            logger: true
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true