NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

sic:
    resource: AppBundle\Controller\SICsController
    prefix:   api/v1
    type:     rest