services:
    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments:
            - "@doctrine_mongodb"
        tags:
            - { name: request.param_converter, converter: doctrine.odm }

    uci.sic:
        class: AppBundle\Services\SIC
        arguments:
            dm: '@doctrine_mongodb'

    uci.company:
        class: AppBundle\Services\Company
        arguments:
            dm: '@doctrine_mongodb'